version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: bookstore-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: bookstoredb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - bookstore-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/bookstoredb --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend GraphQL API
  api:
    build:
      context: ./BookStore
      dockerfile: Dockerfile
    container_name: bookstore-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - MongoDbConfiguration__ConnectionString=mongodb://admin:admin123@mongodb:27017
      - MongoDbConfiguration__Database=bookstoredb
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - bookstore-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Angular Application
  frontend:
    build:
      context: ./BookStore/client
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

